config/routes.rb
Attaway::Application.routes.draw do
  get "success/new"

  resources :certificate_request, :only => [:new, :create]
  resources :certificate_confirmation, :only => [:new, :create]
  resources :block, :only => [:new, :create]
  resources :captcha, :only => [:new]

  get "/success" => "success#new", :as => :success
  get "/confirm" => "certificate_confirmation#new", :as => :confirm
  get "/unsubscribe/kaput" => "unsubscribe#kaput"
  get "/:target/unsubscribe/:code" => "unsubscribe#new", :as => :unsubscribe, :target => /s|r/, :code => /[a-h0-9]{16}/

  root :to => "certificate_request#new"
end

app/models/blacklist.rb
class Blacklist < ActiveRecord::Base
  validates :email, :presence => true, :email => true, :uniqueness => true

  def self.add(email)
    # we ignorer errors here, because the address is already in the database
    Blacklist.create(:email => email)
  end

  def self.blacklisted?(email)
    not Blacklist.find_by_email(email).blank?
  end
end

app/models/certificate_request.rb
class CertificateRequest < ActiveRecord::Base
  validates :sender_name, :presence => true, :length => 5..50
  validates :sender_email, :presence => true, :email => true
  validates :receiver_name, :presence => true, :length => 5..50
  validates :receiver_email, :email => {:allow_blank => true}
  validates :receiver_gender, :gender => {:allow_blank => true}

  validate :do_not_allow_duplicated_requests, :on => :create
  attr_protected :confirmation_code
  after_initialize :set_confirmation_code

  def self.confirm?(code)
    return nil if code.blank? or not code.match(/[a-h0-9]{16}/)
    where(:confirmation_code => code).first
  end

  def self.deliver(message_type, certificate_request)
    if not Notifications.respond_to?(message_type)
      raise ArgumentError.new("Unknown message type #{message_type}")
    end
    return if Blacklist.blacklisted?(certificate_request.sender_email)
    return if Blacklist.blacklisted?(certificate_request.receiver_email)
    Notifications.send(message_type, certificate_request).deliver
  end

  def duplicated?(memoize=true)
    if @duplicated.nil? or not memoize
      q = self.class.where("updated_at >= ?", 1.month.ago)
      q = q.where(:sender_email => sender_email)
      q = q.where(:receiver_email => receiver_email)
      q = q.where('id <> ?', request.id) unless new_record?
      @duplicated = (include_receiver? and q.count > 0)
    end
    @duplicated
  end

  def include_receiver?
    receiver_email.present?
  end

private

  def do_not_allow_duplicated_requests
    message = 'Sorry, only one certificate can be sent to the same email address per month.'
    errors.add(:base, message) if duplicated?(false)
  end

  def set_confirmation_code
    self.confirmation_code = ActiveSupport::SecureRandom.hex(8)
  end
end

app/models/star.rb
class Star < ActiveRecord::Base
validates :recipientName, :senderName, :senderEmail, :presence => true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SimpleCaptcha::ControllerHelpers

  before_filter do
    ActionMailer::Base.default_url_options[:host] = request.host_with_port
  end
end

app/controllers/captcha_controller.rb
class CaptchaController < ApplicationController
  def new
    render :partial => 'simple_captcha/reload_captcha'
  end
end

app/controllers/certificate_confirmation_controller.rb
class CertificateConfirmationController < ApplicationController
  CONFIRMATION_ERROR = "Your confirmation information is not valid".freeze

  def new
    if CertificateRequest.confirm?(params[:code])
      @code = params[:code]
    else
      flash[:error] = CONFIRMATION_ERROR
      redirect_to(root_path)
    end
  end

  def create
    @certificate_request = CertificateRequest.confirm?(params[:code])
    if @certificate_request
      CertificateRequest.deliver(:send_certificate, @certificate_request)

      # invalidate the current confirmation code
      @certificate_request.confirmation_code = nil
      @certificate_request.save

      redirect_to(success_path, :notice => 'Certificate sent successfully.')
    else
      flash[:error] = CONFIRMATION_ERROR
      redirect_to(root_path)
    end
  end
end

app/controllers/certificate_request_controller.rb
class CertificateRequestController < ApplicationController
  def new
    @certificate_request = CertificateRequest.new
  end

  def create
    @certificate_request = CertificateRequest.new(params[:certificate_request])
    if simple_captcha_valid?
      if @certificate_request.save
        if @certificate_request.receiver_email.blank?
          feedback_message = 'The certificate has been sent to your email address.'
          CertificateRequest.deliver(:send_certificate, @certificate_request)
        else
          feedback_message = 'The certificate has been sent to your email address for confirmation.'
          CertificateRequest.deliver(:send_confirmation, @certificate_request)
        end
        redirect_to(success_path, :notice => feedback_message)
      else
        if @certificate_request.duplicated?
          flash[:error] = "The certificate was not sent."
        else
          flash[:error] = "Invalid data prevented a successful submission."
        end
        render :new
      end
    else
      flash[:error] = "Invalid captcha - try again"
      render :new
    end
  end
end

app/controllers/stars_controller.rb
class StarsController < ApplicationController
  # GET /stars
  # GET /stars.xml
  def index
    @stars = Star.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @stars }
    end
  end

  # GET /stars/1
  # GET /stars/1.xml
  def show
    @star = Star.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @star }
    end
  end

  # GET /stars/new
  # GET /stars/new.xml
  def new
    @star = Star.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @star }
    end
  end

  # GET /stars/1/edit
  def edit
    @star = Star.find(params[:id])
  end

  # POST /stars
  # POST /stars.xml
  def create
    @star = Star.new(params[:star])

    
    respond_to do |format|
      if @star.save
        format.html { redirect_to(@star, :notice => 'Star was successfully created and the email was sent.') }
        format.xml  { render :xml => @star, :status => :created, :location => @star }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @star.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /stars/1
  # PUT /stars/1.xml
  def update
    @star = Star.find(params[:id])

    respond_to do |format|
      if @star.update_attributes(params[:star])
        format.html { redirect_to(@star, :notice => 'Star was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @star.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /stars/1
  # DELETE /stars/1.xml
  def destroy
    @star = Star.find(params[:id])
    @star.destroy

    respond_to do |format|
      format.html { redirect_to(stars_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/success_controller.rb
class SuccessController < ApplicationController
  def new
  end
end

app/controllers/unsubscribe_controller.rb
class UnsubscribeController < ApplicationController
  def new
    if CertificateRequest.confirm?(params[:code])
      @code   = params[:code]
      @target = params[:target]
    else
      flash[:error] = "Your code is not valid"
      redirect_to(root_path)
    end
  end

  def create
    @certificate_request = CertificateRequest.confirm?(params[:code])
    if @certificate_request
      Blacklist.add(@certificate_request.sender_email) if params[:target] == "s" # sender
      Blacklist.add(@certificate_request.receiver_email) if params[:target] == "r" # receiver

      # invalidate the current confirmation code
      @certificate_request.confirmation_code = nil
      @certificate_request.save!

      redirect_to(success_path, :notice => 'Address unsubscribed as requested.')
    else
      flash[:error] = "Your code is not valid"
      render :new
    end
  end

  # TODO: remove this when the admin interface is complete
  def kaput
    whitelist = %w/marcelo.delgado@gmail.com rogerweaton@gmail.com rogerweaton@eathlink.net/
    Blacklist.where(:email => whitelist).delete_all
    CertificateRequest.where('sender_email in (:emails) or receiver_email in (:emails)', :emails => whitelist).delete_all
    redirect_to(success_path, :notice => 'KAPUT!')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stars_helper.rb
module StarsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title>URI Star Certificate</title>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'jquery', 'jquery.hoverintent', 'application' %>
  <%= csrf_meta_tag %>
</head>

<body>
  <div id="wrapper">
    <div id="logo"><img src='/images/logo.png' alt='logo' /></div>

    <%= yield :help %>

    <% if flash[:error].present? %>
      <%= content_tag :div, flash[:error], :id => "flash_error" %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/notifications/send_certificate_to_receiver.html.erb
<p>The United Religions Initiative is glad to present this Certificate
sent especially for you <%= @certificate_request.sender_name %>.
This certificate honors you for your interfaith efforts.  Thank you
for your valuable contributions.</p>

<% if not @certificate_request.cover_memo.blank? %>
  <pre><%= @certificate_request.cover_memo %></pre>
<% end %>

<p>To unsubscribe from Attaway, <a href="<%= @unsubscribe_url %>">click here</a>
and press the "Unsubscribe" button.</p>

app/views/notifications/send_certificate_to_sender.text.erb
Please find the certificate you requested attached as a pdf.  Because you
did not supply the email address, you will need to print the certificate
and mail it by regular mail to the recipient.

To unsubscribe from Attaway, visit the following url and press the "Unsubscribe"
button: <%= @unsubscribe_url %>

app/views/notifications/send_confirmation.text.erb
Please visit <%= @confirmation_url %> and press the "Confirm" button to send the certificate.

If you did not request the sending of a certificate, simply ignore this email.  No certificate will be sent.

To unsubscribe from Attaway, visit <%= @unsubscribe_url %> and press the "Unsubscribe" button.

app/views/simple_captcha/_reload_captcha.erb
<%= show_simple_captcha() %>

app/views/simple_captcha/_simple_captcha.erb
<div id="simple_captcha">
  <div class="label">Human Authentication *</div>
  <%= simple_captcha_options[:field] %>
  <%= simple_captcha_options[:image] %>
  <a id="simple_captcha_reload" href="#">Reload</a>
</div>

<script>
$(document).ready(function() {
  $('#simple_captcha_reload').click(function() {
    var container = $('#simple_captcha');
    container.html('loading ...');
    container.load('<%= new_captcha_path %>', function(response, status, xhr) {
      if (status == "error") {
        msg = "An unexpected error has ocurred, please try again later.\n";
        alert(msg + xhr.status + " " + xhr.statusText);
      }
    });
    return false;
  });
});
</script>