config/routes.rb
Attaway::Application.routes.draw do
  get "success/new"

  resources :certificate_request, :only => [:new, :create]
  resources :certificate_confirmation, :only => [:new, :create]
  resources :block, :only => [:new, :create]
  resources :captcha, :only => [:new]

  get "/success" => "success#new", :as => :success
  get "/confirm" => "certificate_confirmation#new", :as => :confirm
  get "/unsubscribe/kaput" => "unsubscribe#kaput"
  get "/:target/unsubscribe/:code" => "unsubscribe#new", :as => :unsubscribe, :target => /s|r/, :code => /[a-h0-9]{16}/

  root :to => "certificate_request#new"
end

app/models/blacklist.rb
class Blacklist < ActiveRecord::Base
  validates :email, :presence => true, :email => true, :uniqueness => true

  def self.add(email)
    # we ignorer errors here, because the address is already in the database
    Blacklist.create(:email => email)
  end

  def self.blacklisted?(email)
    not Blacklist.find_by_email(email).blank?
  end
end

app/models/certificate_request.rb
class CertificateRequest < ActiveRecord::Base
  validates :sender_name, :presence => true, :length => 5..50
  validates :sender_email, :presence => true, :email => true
  validates :receiver_name, :presence => true, :length => 5..50
  validates :receiver_email, :email => {:allow_blank => true}
  validates :receiver_gender, :gender => {:allow_blank => true}

  validate :do_not_allow_duplicated_requests, :on => :create
  attr_protected :confirmation_code
  after_initialize :set_confirmation_code

  def self.confirm?(code)
    return nil if code.blank? or not code.match(/[a-h0-9]{16}/)
    where(:confirmation_code => code).first
  end

  def self.deliver(message_type, certificate_request)
    if not Notifications.respond_to?(message_type)
      raise ArgumentError.new("Unknown message type #{message_type}")
    end
    return if Blacklist.blacklisted?(certificate_request.sender_email)
    return if Blacklist.blacklisted?(certificate_request.receiver_email)
    Notifications.send(message_type, certificate_request).deliver
  end

  def duplicated?(memoize=true)
    if @duplicated.nil? or not memoize
      q = self.class.where("updated_at >= ?", 1.month.ago)
      q = q.where(:sender_email => sender_email)
      q = q.where(:receiver_email => receiver_email)
      q = q.where('id <> ?', request.id) unless new_record?
      @duplicated = (include_receiver? and q.count > 0)
    end
    @duplicated
  end

  def include_receiver?
    receiver_email.present?
  end

private

  def do_not_allow_duplicated_requests
    message = 'Sorry, only one certificate can be sent to the same email address per month.'
    errors.add(:base, message) if duplicated?(false)
  end

  def set_confirmation_code
    self.confirmation_code = ActiveSupport::SecureRandom.hex(8)
  end
end

app/models/star.rb
class Star < ActiveRecord::Base
validates :recipientName, :senderName, :senderEmail, :presence => true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SimpleCaptcha::ControllerHelpers

  before_filter do
    ActionMailer::Base.default_url_options[:host] = request.host_with_port
  end
end

app/controllers/captcha_controller.rb
class CaptchaController < ApplicationController
  def new
    render :partial => 'simple_captcha/reload_captcha'
  end
end

app/controllers/certificate_confirmation_controller.rb
class CertificateConfirmationController < ApplicationController
  CONFIRMATION_ERROR = "Your confirmation information is not valid".freeze

  def new
    if CertificateRequest.confirm?(params[:code])
      @code = params[:code]
    else
      flash[:error] = CONFIRMATION_ERROR
      redirect_to(root_path)
    end
  end

  def create
    @certificate_request = CertificateRequest.confirm?(params[:code])
    if @certificate_request
      CertificateRequest.deliver(:send_certificate, @certificate_request)

      # invalidate the current confirmation code
      @certificate_request.confirmation_code = nil
      @certificate_request.save

      redirect_to(success_path, :notice => 'Certificate sent successfully.')
    else
      flash[:error] = CONFIRMATION_ERROR
      redirect_to(root_path)
    end
  end
end

app/controllers/certificate_request_controller.rb
class CertificateRequestController < ApplicationController
  def new
    @certificate_request = CertificateRequest.new
  end

  def create
    @certificate_request = CertificateRequest.new(params[:certificate_request])
    if simple_captcha_valid?
      if @certificate_request.save
        if @certificate_request.receiver_email.blank?
          feedback_message = 'The certificate has been sent to your email address.'
          CertificateRequest.deliver(:send_certificate, @certificate_request)
        else
          feedback_message = 'The certificate has been sent to your email address for confirmation.'
          CertificateRequest.deliver(:send_confirmation, @certificate_request)
        end
        redirect_to(success_path, :notice => feedback_message)
      else
        if @certificate_request.duplicated?
          flash[:error] = "The certificate was not sent."
        else
          flash[:error] = "Invalid data prevented a successful submission."
        end
        render :new
      end
    else
      flash[:error] = "Invalid captcha - try again"
      render :new
    end
  end
end

app/controllers/stars_controller.rb
class StarsController < ApplicationController
  # GET /stars
  # GET /stars.xml
  def index
    @stars = Star.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @stars }
    end
  end

  # GET /stars/1
  # GET /stars/1.xml
  def show
    @star = Star.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @star }
    end
  end

  # GET /stars/new
  # GET /stars/new.xml
  def new
    @star = Star.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @star }
    end
  end

  # GET /stars/1/edit
  def edit
    @star = Star.find(params[:id])
  end

  # POST /stars
  # POST /stars.xml
  def create
    @star = Star.new(params[:star])

    
    respond_to do |format|
      if @star.save
        format.html { redirect_to(@star, :notice => 'Star was successfully created and the email was sent.') }
        format.xml  { render :xml => @star, :status => :created, :location => @star }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @star.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /stars/1
  # PUT /stars/1.xml
  def update
    @star = Star.find(params[:id])

    respond_to do |format|
      if @star.update_attributes(params[:star])
        format.html { redirect_to(@star, :notice => 'Star was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @star.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /stars/1
  # DELETE /stars/1.xml
  def destroy
    @star = Star.find(params[:id])
    @star.destroy

    respond_to do |format|
      format.html { redirect_to(stars_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/success_controller.rb
class SuccessController < ApplicationController
  def new
  end
end

app/controllers/unsubscribe_controller.rb
class UnsubscribeController < ApplicationController
  def new
    if CertificateRequest.confirm?(params[:code])
      @code   = params[:code]
      @target = params[:target]
    else
      flash[:error] = "Your code is not valid"
      redirect_to(root_path)
    end
  end

  def create
    @certificate_request = CertificateRequest.confirm?(params[:code])
    if @certificate_request
      Blacklist.add(@certificate_request.sender_email) if params[:target] == "s" # sender
      Blacklist.add(@certificate_request.receiver_email) if params[:target] == "r" # receiver

      # invalidate the current confirmation code
      @certificate_request.confirmation_code = nil
      @certificate_request.save!

      redirect_to(success_path, :notice => 'Address unsubscribed as requested.')
    else
      flash[:error] = "Your code is not valid"
      render :new
    end
  end

  # TODO: remove this when the admin interface is complete
  def kaput
    whitelist = %w/marcelo.delgado@gmail.com rogerweaton@gmail.com rogerweaton@eathlink.net/
    Blacklist.where(:email => whitelist).delete_all
    CertificateRequest.where('sender_email in (:emails) or receiver_email in (:emails)', :emails => whitelist).delete_all
    redirect_to(success_path, :notice => 'KAPUT!')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stars_helper.rb
module StarsHelper
end

app/views/certificate_confirmation/new.html.erb
<h3>Confirmation Request</h3>

<%= form_tag(certificate_confirmation_index_path) do %>
  <%= hidden_field_tag :code, @code %>
  <%= submit_tag 'Confirm' %>
<% end %>

app/views/certificate_request/new.html.erb
<%= content_for :help do %>
<div id="hlp_qm">
  <img src='/images/help.png' alt='help' />
  <div id="hlp_info">
    <p>Add your name and email as the "sender".  You will receive a pdf copy
    of the certificate so you can see exactly what you are sending.</p>

    <p>If you supply the email address of the recipient, you will be asked to
    confirm your request.  This prevents misuse and also gives you a chance to
    review the certificate before it is sent.  Otherwise, you will need to
    print the certificate and mail it by regular mail to the person being
    honored.  The receiver will not be automatically subscribed to any email
    lists.</p>

    <p>The gender of the recipient allows the text of the certificate to say
    "his" or "hers" instead of an awkward "your".</p>

    <p>The cover memo will be included in the email with the certificate.  If
    you do not give the email of the recipient, there is no sense filling in
    the cover memo.</p>

    <p align="right"><a id="hlp_close" href="#">Close</a></p>
  </div>
</div>
<% end %>

<h3>Send URI Interfaith Star</h3>

<%= form_for(@certificate_request, :url => {:action => "create"}) do |f| %>
  <% if @certificate_request.errors.any? %>
  <div id="error_explanation">
  <h2><%= pluralize(@certificate_request.errors.count, "error") %> prohibited this record from being saved:</h2>
  <ul>
    <% @certificate_request.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
  </div>
  <% end %>

  <h2>Sender Options</h2>
  <p>
    <div class="label">Sender Name *</div>
    <%= f.text_field :sender_name %>
  </p>
  <p>
    <div class="label">Sender Email *</div>
    <%= f.text_field :sender_email %>
  </p>

  <h2>Receiver Options</h2>
  <p>
    <div class="label">Receiver Name *</div>
    <%= f.text_field :receiver_name %>
  </p>
  <p>
    <div class="label">Receiver Email</div>
    <%= f.text_field :receiver_email %>
  </p>
  <p>
    <div class="label">Receiver Gender</div>
    <%= f.select :receiver_gender, options_for_select(GenderValidator::GENDERS, :selected => @certificate_request.receiver_gender), {:include_blank => true} %>
  </p>

  <h2>Cover memo</h2>
  <p>
    <div class="label">&nbsp;</div>
    <%= f.text_area :cover_memo %>
  </p>

  <h2>Captcha</h2>
  <%= render 'simple_captcha/reload_captcha', :target => :certificate_request %>

  <p class="button" align="center">
    <%= f.submit "Request" %>
  </p>
<% end %>

app/views/stars/_form.html.erb
<%= form_for(@star) do |f| %>
  <% if @star.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@star.errors.count, "error") %> prohibited this star from being saved:</h2>
      <ul>
      <% @star.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field" style='visibility:hidden'>
    <%= f.label :id %><br />
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label 'Recipient Name' %><br />
    <%= f.text_field :recipientName %>
  </div>
  <div class="field">
    <%= f.label 'Recipient Email' %><br />
    <%= f.text_field :recipientEmail %>
  </div>
  <div class="field">
    <%= f.label 'Sender Name' %><br />
    <%= f.text_field :senderName %>
  </div>
  <div class="field">
    <%= f.label 'Sender Email' %><br />
    <%= f.text_field :senderEmail %>
  </div>
  <div class="field">
    <%= f.label 'Certificate Date' %><br />
    <%= f.text_field :certificateDate %>
  </div>
  <div class="field"  style='visibility:hidden'>
    <%= f.label :creationDate %><br />
    <%= f.date_select :creationDate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stars/edit.html.erb
<h1>Editing star</h1>

<%= render 'form' %>

<%= link_to 'Show', @star %> |
<%= link_to 'Back', stars_path %>

app/views/stars/index.html.erb
<h1>Listing stars</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Recipient Name</th>
    <th>Recipient Email</th>
    <th>Sender Name</th>
    <th>Sender Email</th>
    <th>Certificate Date</th>
    <th>Creation Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stars.each do |star| %>
  <tr>
    <td><%= star.id %></td>
    <td><%= star.recipientName %></td>
    <td><%= star.recipientEmail %></td>
    <td><%= star.senderName %></td>
    <td><%= star.senderEmail %></td>
    <td><%= star.certificateDate %></td>
    <td><%= star.creationDate %></td>
    <td><%= link_to 'Show', star %></td>
    <td><%= link_to 'Edit', edit_star_path(star) %></td>
    <td><%= link_to 'Destroy', star, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Star', new_star_path %>

app/views/stars/new.html.erb
<h1>New star</h1>

<%= render 'form' %>

<%= link_to 'Back', stars_path %>

app/views/stars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @star.id %>
</p>

<p>
  <b>Recipientname:</b>
  <%= @star.recipientName %>
</p>

<p>
  <b>Recipientemail:</b>
  <%= @star.recipientEmail %>
</p>

<p>
  <b>Sendername:</b>
  <%= @star.senderName %>
</p>

<p>
  <b>Senderemail:</b>
  <%= @star.senderEmail %>
</p>

<p>
  <b>Certificatedate:</b>
  <%= @star.certificateDate %>
</p>

<p>
  <b>Creationdate:</b>
  <%= @star.creationDate %>
</p>


<%= link_to 'Edit', edit_star_path(@star) %> |
<%= link_to 'Back', stars_path %>

app/views/success/new.html.erb
<h3>Success!</h3>
<h4><%= flash[:notice] %></h4>

app/views/unsubscribe/new.html.erb
<h3>Unsubscribe all URI interfaith star communications</h3>
<%= form_tag(unsubscribe_index_path) do %>
  <%= hidden_field_tag :code, @code %>
  <%= submit_tag 'Unsubscribe' %>
<% end %>